@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

:Get the duplicate company\n          from the model;
:Get the index of the duplicate company from the \n                 filtered company list panel;
if () then ([else])
    :Get the index of the duplicate company from the \n                     full company list panel;
else ([Duplicate company is in filtered company list panel])
    endif

:Get a message string of changed fields between the \n   duplicate company and the company to be added;
:Format the error message for the user \n         using the fields and the index;
stop
@enduml
